---
apiVersion: v1
kind: Secret
metadata:
  name: s3fuse-credentials-secret
  namespace: s3fuse
type: Opaque
data:
  # echo -n "passwd" | base64 -w 0
  # echo "aws_secret_access_hey" | base64
  secret-access-key: captain
---
apiVersion: v1
kind: Namespace
metadata:
  name: s3fuse
